const message = {
  USER_REGISTRATION: "User Registration successfully!",
  USER_LOGIN: "User login successfully!",
  ERROR_MESSAGE: "Unexpected error occurred!",
  PASSWORD_REQUIRED: "Password is required! ",
  PASSWORD_CHARACTER: "Password must be at least 8 characters long!",
  PASSWORD_MATCH: "Password not match,please check your password!",
  PASSWORD_REQUIRED_CHARACTER: "Password must be at least 8 characters long!",
  PASSWORD_NOT_MATCH: "Password did not match,please check your password!",
  EMAIL_ALREADY_EXISTS: "Email already exists please enter another email!",
  EMAIL_PASSWORD_WRONG: "Email and Password Wrong!",
  DATA_NOT_FOUND: "User data not found!",
  ALREADY_EXISTS: "You are already exists!",
  EMAIL_NOT_MATCH: "This email address does not exists!",
  EMAIL_VERIFIED: "Email verified successfully!",
  PASSWORD_UPDATED: "Password updated successfully!",
  ADMIN_PROFILE_UPDATE: "Admin profile update successfully!",
  USER_LOGOUT: "User logout successfully!",
  NEWS_DATA_CREATED: "News data created successfully!",
  NEWS_DATA_UPDATED: "News data updated successfully!",
  NEWS_DATA_DETAILS: "News data details successfully!",
  NEWS_DATA_DELETED: "News data deleted successfully!",
  ALREADY_DELETED: "Data alredy deleted successfully!",
  PASSWORD_INCORRECT: "Password incorrect ,plese check your password!",
  PASSWORD_CHECKED: "Password mismatch,please check your password!",
  PASSWORD_NOT_UPDATED: "Password did n't updated!",
  CHANGED_PASSWORD: "Password change successfully!",
  OLD_PASSWORD: "Incorrect password,Please check your old password!",
  CONFIRM_PASSWORD: "Confirm password is required",
  HEADER_CREATED: "Header created successfully!",
  HEADERDETAILS_SUCCESS: "Header details get data successfully! ",
  CARD_ADDED: "Card data added successfully!",
  GET_CARD: "Card data get successfully!",
  IMAGEICON_ADDED: "Image icon added successfully!",
  GET_IMAGE_DATA: "Image data get successfully!",
  REVIEWS_ADDED: "Reviews created successfully!",
  GET_REVIEWS: "Reviews data get successfully!",
  CONTENT_ADDED: "Content data added successfully!",
  GET_CONTENT: "Content data get........!",
  HELP_ADDED: "Help data added successfully!",
  SECTION_ADDED: "Section data added successfully!",
  SECTION_UPDATED: "Section data updated successfully!",
  DEMO_ADDED: "Demo data added successfully!",
  BLOG_ADDED: "Blog data added successfully!",
  BLOG_DATA_LIST: "Blog data list!",
  GET_BLOG: "Blog data get successfully!",
  BLOG_UPDATED: "Blog data updated successfully!",
  BLOG_DELETED: "Blog data deleted successfully!",
  ECOMMERCE_ADDED: "E-commerce data added successfully!",
  PARAGRAPH_ADDED: "Paragraph data created successfully!",
  GET_HEADER: "Header dat get successfully!",
  GET_IMAGEICON: "Image icon get successfully!",
  GET_SECION: "Section data get successfully!",
  SERVICE_DATA_ADDED: "Service data created successfully!",
  GET_SERVICE: "Service data get successfully!",
  GET_PARAGRAPH_DATA: "Paragraph data get successfully!",
  CONTACT_INFORMATION_ADDED: "Contact information details save successfully!",
  CASE_LIST: "Case data list get successfully!",
  DELETED_CASE_DATA: "Case data deleted successfully!",
  DELETED_CONTACT_DATA: "Contact data deleted successfully!",
  DEMO_UPDATE: "Demo data update successfully!",
  UPDATE_HEADER: "Update header data successfully!",
  CARD_ADDED: "Cards added successfully!",
  CARD_DETAILS: "Card details fetch successfully!",
  Card_UPDATED: "Card updated successfully!",
  SECTION_ADDED: "Section created successfully!",
  SECTION_DETAILS: "Section details fetch successfully!",
  SECTION_UPDATED: "Section updated succcessfully!",
  ADD_HIRING_DATA: "Hiring darta add successfully!",
  GET_HIRING_DATA: "Hiring data fetching successfully!",
  SUCCESS_CATEGORY_ADDED: "Success category created successfully!",
  STORY_ADDED: "Story data created successfully!",
  STORY_DETAILS: "Story details fetch successfully!",
  STORY_UPDATED: "Story updated succcessfully!",
  STORY_UPDATED_IMAGE: "Story image updated successfully!",
  STORY_DELETED:"Story deleted successfully!",
  CONTACT_DETAILS:"Contact details fetch successfully",
  HIRING_DETAILS:"Hiring contact details fetch successfully",
  SERVICE_ADDED:"Service header added succesfully",
  SERVICE_DETAILS:"Service header details fetch",
  SERVICE_UPDATE:"Service header updated successfully",
  SERVICE_DELETE:"Service deleted successfully",
  SERVICE_PARA_ADD:"Sevice paragraph add successfully",
  SERVICE_PARA_DETAILS:"Service paragraph details fetch",
  SERVICE_PARA_UPDATE:"Service paragraph update successfully",
  SERVICE_PARA_DELETE:"Service paragraph delete",
  CARDS_ADD:"Service cards add successfully",
  CARDS_DETAILS:"Service cards details",
  CARDS_UPDATE:"Service cards update",
  CARDS_DELETE:"Service cards delete",
  
};
module.exports = {
  message,
};
